/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    BatchedTagEditor: typeof import('./components/BatchedTagEditor.vue')['default']
    DatabaseMaintenance: typeof import('./components/DatabaseMaintenance.vue')['default']
    DataImporter: typeof import('./components/DataImporter.vue')['default']
    DatasourceCreation: typeof import('./components/DatasourceCreation.vue')['default']
    DatasourceCreationArgon2ParametersProbing: typeof import('./components/DatasourceCreationArgon2ParametersProbing.vue')['default']
    DatasourceCreationEntryBase: typeof import('./components/DatasourceCreationEntryBase.vue')['default']
    DatasourceCreationEntryRating: typeof import('./components/DatasourceCreationEntryRating.vue')['default']
    DatasourceCreationEntrySetting: typeof import('./components/DatasourceCreationEntrySetting.vue')['default']
    DatasourceCreationEntryString: typeof import('./components/DatasourceCreationEntryString.vue')['default']
    DatasourceCreationEntryTag: typeof import('./components/DatasourceCreationEntryTag.vue')['default']
    DatasourceCreationGeneralConfiguration: typeof import('./components/DatasourceCreationGeneralConfiguration.vue')['default']
    DatasourceCreationKeysConfiguration: typeof import('./components/DatasourceCreationKeysConfiguration.vue')['default']
    DatasourceCreationSecuritySetup: typeof import('./components/DatasourceCreationSecuritySetup.vue')['default']
    DatasourceCreationWelcome: typeof import('./components/DatasourceCreationWelcome.vue')['default']
    DatasourceSelector: typeof import('./components/DatasourceSelector.vue')['default']
    HoverableRating: typeof import('./components/HoverableRating.vue')['default']
    ItemEditor: typeof import('./components/ItemEditor.vue')['default']
    ItemRatingDisplay: typeof import('./components/ItemRatingDisplay.vue')['default']
    ItemRatingEditor: typeof import('./components/ItemRatingEditor.vue')['default']
    ItemStringDisplay: typeof import('./components/ItemStringDisplay.vue')['default']
    ItemStringEditor: typeof import('./components/ItemStringEditor.vue')['default']
    ItemTagDisplay: typeof import('./components/ItemTagDisplay.vue')['default']
    ItemTagEditor: typeof import('./components/ItemTagEditor.vue')['default']
    ItemViewer: typeof import('./components/ItemViewer.vue')['default']
    LanguageSelector: typeof import('./components/LanguageSelector.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagInsight: typeof import('./components/TagInsight.vue')['default']
    VennDiagram: typeof import('./components/VennDiagram.vue')['default']
  }
}
